version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "text to output here" > output.txt
      - persist_to_workspace:
          root: /
          paths: 
            - output.txt

  print_output_file:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - attach_workspace:
          at: /
      - run: cat output.txt


  print-my-name:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "My name is $USER_NAME"        

workflows:
  my-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - print-my-name    
