version: 2.1

jobs:
  print-hello:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello!"

  print-world:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "world!"

  print-my-name:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "My name is $USER_NAME"        

workflows:
  my-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - print-my-name:
          requires:
            - print-world      
