version: 2.1

commands: 
  print_pipeline_id:
    description: "Print Circle CI workflow Id"
    steps:
      - run: 'echo "Workflow id: $CIRCLE_WORKFLOW_ID"'   
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "text to output here" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt

  print_output_file:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt


  print-my-name:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "My name is $USER_NAME"   
      - run: 
        name: "Test failure"
        command: echo "Test"
        when: on_fail   

  use-command: 
    docker:
      - image: cimg/node:17.2.0 
    steps:
      - print_pipeline_id     

  failure-test: 
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: return 1 
      - run: 
        name: "Test failure"
        command: echo "Failure tested successfuly"
        when: on_fail   
        

workflows:
  my-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - print-my-name    
      - use-command
      - failure-test
