version: 2.1

default_runner: &default_runner
  docker: 
    - image: cimg/node:17.2.0
    
commands: 
  print_pipeline_id:
    description: "Print Circle CI workflow Id"
    steps:
      - run: 'echo "Workflow id: $CIRCLE_WORKFLOW_ID"'   
jobs:
  save_hello_world_output:
    <<: *default_runner 
    steps:
      - checkout
      - run: echo "text to output here" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt

  print_output_file:
    <<: *default_runner 
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt


  print-my-name:
    <<: *default_runner 
    steps:
      - run: echo "My name is $USER_NAME"   

  use-command: 
    <<: *default_runner 
    steps:
      - print_pipeline_id     

  failure-test: 
    <<: *default_runner 
    steps:
      - run: return 1 
      - run: 
          name: "Test failure"
          command: echo "Failure tested successfuly"
          when: on_fail   
        

workflows:
  my-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - print-my-name    
      - use-command
      - failure-test
